(() => {
 const headline=document.querySelector('[data-elem-id="1791098052216000015"] .tn-atom');if(!headline)return;
 const panel=document.createElement('section');panel.id='md-project-details';panel.setAttribute('aria-live','polite');document.body.append(panel);
 const data=Object.fromEntries([...document.querySelectorAll('#md-project-content [data-project-key]')].map(el=>[el.dataset.projectKey,{title:el.querySelector('h2').textContent.trim(),description:el.querySelector('p').textContent.trim(),tasks:[...el.querySelectorAll('li')].map(li=>li.textContent.trim())}]));
 let active=null,frame=0,exitTimer;
 function align(){const rect=headline.getBoundingClientRect(),font=getComputedStyle(headline),scale=rect.width/Math.max(1,headline.offsetWidth);Object.assign(panel.style,{left:rect.left+'px',top:rect.top+'px',width:rect.width+'px',fontFamily:font.fontFamily});panel.style.setProperty('--project-title-size',parseFloat(font.fontSize)*scale+'px');const nav=document.querySelector('.md-nav-link');if(nav){const f=getComputedStyle(nav);panel.style.setProperty('--project-body-size',parseFloat(f.fontSize)*nav.getBoundingClientRect().height/Math.max(1,nav.offsetHeight)+'px');}const clock=document.querySelector('.vlad .tn-atom');if(clock)panel.style.setProperty('--project-task-top',(clock.getBoundingClientRect().top-rect.top)+'px');}
 function show(card){clearTimeout(exitTimer);active=card;cancelAnimationFrame(frame);const key=card.querySelector('.md-work-card__title')?.dataset.projectTitle||card.querySelector('.md-work-card__title')?.textContent.trim()||'';window.MD_PROJECT_SPEECH?.(null);const content=data[key];const title=content?.title||key;panel.replaceChildren();const heading=document.createElement('h2');heading.textContent=title;panel.append(heading);if(content){const description=document.createElement('p');description.textContent=window.MD_RU_TEXT(content.description);panel.append(description);const tasks=document.createElement('div');tasks.className='md-project-tasks';content.tasks.forEach(task=>{const line=document.createElement('p');line.textContent=window.MD_RU_TEXT('// '+task);tasks.append(line);});panel.append(tasks);}align();document.documentElement.classList.add('md-project-hover');panel.classList.add('visible');const revealLines=[...panel.querySelectorAll('p')].map((element,index)=>{const text=element.textContent;const spans=[...text].map(character=>{const span=document.createElement('span');span.textContent=character;span.style.opacity='0';element.append(span);return span;});element.replaceChildren(...spans);return {text,spans,delay:index===0?90:180+index*90,last:-1};});const start=performance.now(),chars='АБВГДЕЖЗИКЛМНОПРСТУФХЦЧШЩЭЮЯ0123456789/#%';function tick(now){const progress=Math.min(1,(now-start)/550),settled=Math.floor(title.length*progress);heading.replaceChildren(...[...title].map((c,i)=>{const span=document.createElement('span');const random=i>=settled&&!/\s/u.test(c);span.textContent=random?chars[Math.floor(Math.random()*chars.length)]:c;if(random)span.style.color='#8950ff';return span;}));for(const line of revealLines){const phase=Math.floor((now-start-line.delay)/30);if(phase===line.last)continue;line.last=phase;line.spans.forEach((span,i)=>{const local=phase-Math.floor(i*14/line.spans.length);if(local<0)return;span.style.opacity='1';const random=local<4&&!/\s/u.test(line.text[i]);span.textContent=random?chars[Math.floor(Math.random()*chars.length)]:line.text[i];span.style.color=random?'#8950ff':'';});}if(now-start<1100)frame=requestAnimationFrame(tick);else window.MD_PROJECT_SPEECH?.(key,{delay:1000});}frame=requestAnimationFrame(tick);}
 function hide(){window.MD_PROJECT_SPEECH?.(null);active=null;cancelAnimationFrame(frame);panel.classList.remove('visible');document.documentElement.classList.remove('md-project-hover');}
 document.addEventListener('pointerover',event=>{const card=event.target.closest('.md-work-card');if(card&&card!==active&&document.getElementById('md-work-slider')?.dataset.mdIntro==='ready')show(card);});
 document.addEventListener('pointerout',event=>{if(active&&event.target.closest('.md-work-card')===active&&!active.contains(event.relatedTarget)){exitTimer=setTimeout(hide,60);}});
 window.addEventListener('resize',align);window.addEventListener('scroll',()=>{if(active)align();},{passive:true});
})();
